name: Update Index Page and README

on:
  push:
    paths:
      - index.html
    branches:
      - main

jobs:
  commit_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update index.html with actor and timestamp
        run: |
          echo "<p>Updated by ${{ github.actor }} on $(date -u)</p>" >> index.html

      - name: Log update in README.md
        run: |
          echo "### Updated by ${{ github.actor }} on $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add index.html README.md
          git commit -m "Automated update by GitHub Actions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
