name: Update Index Page

on:
  push:
    paths:
      - index.html
    branches:
      - main

jobs:
  commit_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update index.html with actor and timestamp
        run: |
          echo "<p>Updated by ${{ github.actor }} on $(date)</p>" >> index.html

      - name: Log update in README.md
        run: |
          echo "Update by ${{ github.actor }} on $(date '+%Y-%m-%d %H:%M:%S')" >> README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add index.html README.md
          git commit -m "Update index.html and README.md with log"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
