name: Update Index Page

on:
  push:
    branches:
      - main

jobs:
  commit_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Modify index.html
        run: echo "<h1>Welcome to My Website</h1>" > index.html

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add index.html
          git commit -m "Update index.html with new content"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
